hay-kot/mealie

- README.md
- docs/docs/1.3 - admin-panel.md
- frontend/src/api/backup.js
- frontend/src/components/Admin/Theme.vue
- frontend/src/components/MealPlan/MealSelect.vue
- mealie/routes/backup_routes.py
- mealie/routes/meal_routes.py
- mealie/services/backup_services.py
This PR adds a small documentation note about variables availible for markdown export templates, fixes typos in function/api route names, and removes incorrect doctests. It also changes the success SnackReponse on the `export_database` route to display the absolute path of the backup file that was created.
Let me know if you'd like me to break this up into separate PRs instead!
> Small additions to documentation and typo fixes + slight backup snackbar modification

- frontend/src/components/Recipe.vue
- frontend/src/components/RecipeEditor/DetailsView.vue
- frontend/src/components/RecipeEditor/EditRecipe.vue
The % opacity css values were all being changed to 1% in my builds, which I belive was due to this issue: https://github.com/cssnano/cssnano/issues/892 so I switched them to specify decimal opacity values instead.
> Updated css % opacity values to fix 1% issue

- frontend/src/components/Admin/ThemeUI/NewTheme.vue
With out the validation, a user can enter a blank theme name. When trying to delete the theme with no name, the call fails, leaving the blank theme there forever.
Blank Theme name: Unable to remove.
First open: Disabled Create
Error state: Added field validation for required.
Successful validation:
> Added Simple Field Validation to New Theme Modal

- Dockerfile.dev
- dev/scripts/scrape_recipe.py
- mealie/services/scrape_services.py
- mealie/test/data/Pizza-Knoblauch-Champignon-Paprika-vegan.html.json
- mealie/test/data/best-homemade-salsa-recipe.json
- mealie/test/data/blue-cheese-stuffed-turkey-meatballs-with-raspberry-balsamic-glaze-2.json
- mealie/test/data/bon_appetit.json
- mealie/test/data/chunky-apple-cake.json
- mealie/test/data/dairy-free-impossible-pumpkin-pie.json
- mealie/test/data/how-to-make-instant-pot-spaghetti.json
- mealie/test/data/instant-pot-chicken-and-potatoes.json
- mealie/test/data/instant-pot-kerala-vegetable-stew.json
- mealie/test/data/jalapeno-popper-dip.json
- mealie/test/data/microwave_sweet_potatoes_04783.json
- mealie/test/data/moroccan-skirt-steak-with-roasted-pepper-couscous.json
- mealie/test/test_scraper.py
- requirements.dev.txt
Including tests and example recipe data. 
pytest is used as the test framework, hence the new dev dependencies 
The tests can either be run in a local virtualenv
```
TEST_DATA_DIR=mealie/test/data pytest
```
or in the `mealie-api` docker container
```
docker run --rm -it --entrypoint pytest -e "TEST_DATA_DIR=/app/test/data" mealie-api:dev
```
This fixes some, but not all URLs reported in #7. The remaining ones do not contain any `json-ld` metadata or markup and hence cannot be scraped by `scrape_schema_recipe.scrape_url`.
> Normalize recipe instructions, yield, and image url

- mealie/services/scrape_services.py
- mealie/test/test_scraper.py
`normalize_instructions()` would previously treat a `\r\n\r\n` as two lines. In adding more test cases the parametrization has also been simplified to follow the [pytest documentation](https://docs.pytest.org/en/stable/parametrize.html)
> Fix bug in instruction normalization

- README.md
Found an extra s. DESTROYED it.
> Fix link to Docker Hub

- mealie/services/migrations/nextcloud.py
In some cases, Nextcloud names the ,json file with the recipe name (example: Guacamole.json) instead of the default recipe,json.
I also took the liberty to add the stacktrace to the log in case of error.
> Consider any .json file from Nextcloud

- mealie/services/scrape_services.py
Some recipes may not have any instructions, for example cocktails or sauces. They only list ingredients.
This change allows importing recipes without instructions.
> Allow empty instructions

- frontend/src/App.vue
Some components were already loaded before "mounted" is triggered, such as the category sidebar or the top-right menu, leading to strings being displayed in the default English language.
> Initialize language settings earlier

- docs/docs/getting-started/api-usage.md
Update docs [API Usage](https://hay-kot.github.io/mealie/getting-started/api-usage/) page with an example for recipe bulk import.
Bash and Python scripts for bulk import.
> Add bulk import examples to docs.

- frontend/src/components/Login/LoginForm.vue
If the site was in dark mode, fields were black on dark grey.
> Do not force theme settings on login form

- Dockerfile.dev
- docker-compose.dev.yml
- makefile
- mealie/app.py
- mealie/db/init_db.py
- mealie/run.sh
- Changed app_data to /app/dev/data
- app.py is now the single entrypoint: initialization is done there. This was needed because the RUN commands in Dockerfile were broken (initialization was done prior to volume mounts).
I still need to test the docker production build, not sure yet if the initialization in run.sh is still needed.
> Fix docker dev db persistence

- docs/docs/getting-started/install.md
Per issue #249, tip gives guidance for running Mealie in a docker linux/arm/v7 container.
> Add tip to fix rpi host running docker container

- frontend/src/components/Recipe/RecipeViewer/Ingredients.vue
When you search for a new recipe while already viewing one, everything is correctly displayed except for the ingredients list.
> Fix ingredients list not being refreshed upon recipe change

- frontend/src/components/MealPlan/MealPlanNew.vue
Infinite loop would happen if there were more days than recipes.
It would probably be better to enhance the algorithm or at least warn the user, but since it's an edge case it's low prio.
> Fix infinite loop in meal planner randomizer

- docs/docs/site-administration/backups-and-exports.md
- mealie/routes/utility_routes.py
- mealie/services/backups/exports.py
Hi,
I wanted to setup an automatic backup via cronjob but noticed that the docu is not up to date. There's also a small error if the `templates` attribute in `/api/backups/export/database` is not set even though it's marked as optional.
I've also tried to regenerate the swagger json but there's a still an error with the example value in the `template` attribute and I don't know how to fix it:
```json
{
"tag": "July 23rd 2021",
"options": {
"recipes": true,
"settings": true,
"pages": true,
"themes": true,
"groups": true,
"users": true,
"notifications": true
},
"template": [
"recipes.md"
]
}
```
Accordingly to the `BackupJob` model it must be in plural `templates`. The schema in swagger is btw correct, it's just about the example.
> Fixed backup, updated backup docu

- frontend/src/components/Recipe/Parts/Instructions.vue
When switching to a new a recipe from one already displayed, the disabled steps would carry over to the new recipe.
> Reset disabled steps when switching recipe

- frontend/src/i18n.js
- frontend/src/routes/index.js
- frontend/src/store/modules/siteSettings.js
I'm a bit puzzled with the results I've got so far. I followed the documentation but the webpack plugin still shows every language file, only regrouped differently. 
Am I reading this wrong, or does this make no difference on the bundle size? I'm open to feedback.
Fixes #527
> Lazy load translations

- frontend/src/i18n.js
VueI18n defaults to en-US when no language is specified, which prevented en-US messages from being loaded.
> Fix en-US language not being loaded

- frontend/src/components/Fallbacks/The404.vue
- frontend/src/components/UI/SiteLoader.vue
- frontend/src/locales/messages/en-US.json
- frontend/src/plugins/vuetify.js
- frontend/src/store/modules/language.js
Remove support for Danish, Portuguese and Chinese Traditional, since their current translation state is <20% and translation dynamic is poor to null (https://crowdin.com/project/mealie).
NB: this only prevents users from selecting the language in the UI. Users currently using a now unsupported language will see no difference, since the translations are still shipped with Mealie and the database settings are unchanged.
> Remove unmaintained languages + minor localization tasks

- frontend/src/components/Recipe/Parts/Notes.vue
- frontend/src/components/Recipe/RecipePageActionMenu.vue
- frontend/src/pages/Recipe/ViewRecipe.vue
- Leave recipe in edit mode in case of an API error
- Initialize recipe note with empty title
Fixes #586
> Handle untitled note

- mealie/app.py
- mealie/core/config.py
- mealie/routes/debug_routes.py
Credentials is showing when using PostgreSQL, so I'm did some changes.
UI:
Logs:
> Hide DB credentials on logs/frontend

- .github/workflows/dockerbuild.prod.yml
I saw that the github action failed for the latest build and that you adjusted the build script: 
https://github.com/hay-kot/mealie/commit/fa6743110f1dfd3d5bafb5a73b20b6b68330db7f
But the adjustment is missing in the prod action as well.
So this PR makes the same adjustment to the prod action, so hopefully the action will run without issues and the version is released to docker under the `latest` tag.
> Also update build for prod

- mealie/services/image/image.py
All my imports were logging:
```
Error Scraping Image: 'str' object has no attribute 'name'
```
scrape_image() is meant to return Path, not a string
> Fix logging an error on successful image scrape

- docker-compose.dev.yml
The default credentials for login listed in the [documentation](https://hay-kot.github.io/mealie/documentation/admin/user-management/) are updated in this docker-compose file.
> reference default login credentials per the documentation

- frontend/src/pages/Recipe/ViewRecipe.vue
This makes the recipe image clickable.  This is helpful because some people have scans of their recipes with the instructions within the image.  The UI shrinks and only shows a part of the image.  This allows the user to click the image and then see the full version of the recipe image for printing or reading rather than needing to download and extract a zip of the recipe to get to the image.
> Make Recipe Image Clickable
