dev/dev-notes.md, docs/docs/getting-started/site-settings.md, frontend/package.json, frontend/src/App.vue, frontend/src/api/themes.js, frontend/src/components/Admin/Theme.vue, frontend/src/components/Recipe.vue, frontend/src/main.js, frontend/src/store/modules/userSettings.js, frontend/src/store/store.js
Added option for System specific dark mode.
Updated Themes to have one color palette for dark and light to align with the database.
Added confirmation for deleting a theme.
=> Added System Dark Mode, Updated theme settings, Persistent Vuex

frontend/package-lock.json, frontend/package.json
Due to a bug in vuetify, backgrounds were not working correctly on v-btn.
https://github.com/vuetifyjs/vuetify/releases/tag/v2.4.2
> Bug Fixes
VBtn: show background on non-elevated buttons, fix color states (#12908) (a2a61c2), closes #12903 #12892 #12845
=> FIX | Fix button backgrounds

Dockerfile, docker-compose.yml, requirements.txt
shrink production image about 400mb + use pre-configured gunicorn server
=> Dockerfile minification

mealie/app_config.py
Just noticed a minor issue with this error message when I was upgrading to 0.1.0.
Thanks for all your work on this app, really enjoying it. I hope I'll have some time soon to make some more substantive contributions--let me know if there are any areas in particular you're looking for help with.
=> Fix error message

docs/docs/contributors/developers-guide/code-contributions.md
=> Fix link to dev-notes.md

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml
Create the following Issue Templates: 
- Bug Report based on the [Bug Report suggestions in the Mealie docs.](https://hay-kot.github.io/mealie/contributors/developers-guide/code-contributions/#write-bug-reports-with-detail-background-and-sample-code)
- Feature Request which will auto-redirect to the [[META] Feature Request thread](https://github.com/hay-kot/mealie/issues/122).
=> Create Issue Templates

frontend/src/locales/sv.json, frontend/src/store/modules/language.js
- Also change da to Danish and not dutch
=> translation: add swedish

mealie/services/scrape_services.py
Some urls erroneously deliver escaped html their instructions,
sometimes they are even escaped on multiple levels like here:
https://www.ica.se/recept/kladdig-kladdkaka-722982/
```
>>> normalize_instruction("S&amp;auml;tt ugnen p&amp;aring; 200&amp;deg;C.")
'Sätt ugnen på 200°C.'
```
=> scraper: unescape html in instructions

frontend/src/components/Recipe/RecipeEditor/ExtrasEditor.vue, frontend/src/components/Recipe/RecipeEditor/index.vue, frontend/src/components/Recipe/RecipeTimeCard.vue, frontend/src/components/Recipe/RecipeViewer.vue, frontend/src/components/Settings/Backup/NewBackupCard.vue, frontend/src/components/Settings/Backup/index.vue, frontend/src/components/Settings/General/index.vue, frontend/src/components/Settings/Migration/MigrationCard.vue, frontend/src/components/Settings/Migration/index.vue, frontend/src/components/Settings/Theme/NewThemeDialog.vue, frontend/src/components/Settings/Theme/index.vue, frontend/src/components/UI/ButtonRow.vue, frontend/src/components/UI/Confirmation.vue, frontend/src/components/UI/SearchBar.vue, frontend/src/components/UI/UploadBtn.vue, frontend/src/locales/da.json, frontend/src/locales/en.json, frontend/src/locales/fr.json, frontend/src/locales/sv.json, frontend/src/locales/zh-CN.json, frontend/src/locales/zh-TW.json, frontend/src/store/modules/language.js
Fix missing translations key for pages and locale files
Clean up unused value in locale files
Add Simplified Chinese
Add Traditional Chinese
=> Fix missing translations key

mealie/services/scrape_services.py
=> fix scrape recipe error

frontend/src/locales/pl.json, frontend/src/store/modules/language.js
As the title says; reread it twice so it should be at least usable and everything should be spelled correctly.
=> Add polish translation

frontend/src/locales/de.json
This is the German Translation for Mealie.
=> Add German Translation

frontend/src/components/Settings/Backup/AvailableBackupCard.vue, frontend/src/components/Settings/Backup/ImportDialog.vue, frontend/src/components/Settings/Backup/NewBackupCard.vue, frontend/src/components/Settings/Backup/index.vue, frontend/src/components/Settings/General/HomePageSettings.vue, frontend/src/components/Settings/General/index.vue, frontend/src/components/Settings/Migration/MigrationCard.vue, frontend/src/components/Settings/Migration/index.vue, frontend/src/components/Settings/Theme/ColorPickerDialog.vue, frontend/src/components/Settings/Theme/index.vue, frontend/src/components/UI/SuccessFailureAlert.vue
Adjusted some styles/alignments on mobile view for settings page. Refer: [v0.3.0](https://github.com/hay-kot/mealie/projects/2#card-54893494)
Will need someone to test it on real devices especially on iPad/tablet. I don't have the device on hand now.
@hay-kot need you review on this too, let me know if any 😃
=> Enhance mobile view

frontend/src/components/Settings/General/HomePageSettings.vue, frontend/src/components/Settings/MealPlanner/index.vue, frontend/src/locales/en.json, frontend/src/locales/fr.json
Found out some texts were still hardcoded while double-checking FR translations.
=> Localize homepage settings + FR translation

frontend/src/components/UI/CategorySidebar.vue, frontend/src/locales/messages/de.json, frontend/src/locales/messages/en.json, frontend/src/pages/AllRecipesPage.vue, frontend/src/pages/HomePage.vue
Also slightly improved the german translation file.
=> Some titles were missing i18n

docs/docs/changelog/v0.4.1.md, frontend/src/components/Admin/General/CreatePageDialog.vue, frontend/src/components/Admin/General/HomePageSettings.vue, frontend/src/components/Admin/Migration/MigrationCard.vue, frontend/src/components/UI/Dialogs/NewCategoryTagDialog.vue
=> bug-fixes/category-tag-creator

.vscode/tasks.json, mealie/services/image/minify.py, tests/unit_tests/test_cleaner.py
Had 2 errors when running pytests, most likely Windows-specific.
=> Fix some pytests

frontend/src/locales/pt-PT.json, frontend/src/store/modules/language.js
Added  **pt-PT.json** with the Portuguese translation. 
(This represents European Portuguese translation)
=> Add Portuguese Translation

docs/docs/changelog/v0.4.2.md, frontend/src/api/recipe.js, frontend/src/components/Recipe/RecipeEditor/ImageUploadBtn.vue, frontend/src/components/Recipe/RecipeEditor/NutritionEditor.vue, frontend/src/components/Recipe/RecipeEditor/index.vue, frontend/src/components/Recipe/RecipeViewer/index.vue, frontend/src/components/UI/UploadBtn.vue, frontend/src/pages/Recipe/ViewRecipe.vue, mealie/routes/recipe/recipe_crud_routes.py, mealie/services/image/image.py
=> Basic nutrition editor

mealie/services/backups/exports.py, poetry.lock, pyproject.toml
=> Sanitize recipe backup filenames

frontend/src/components/UI/CategorySidebar.vue
=> Display categories in sidebar if no pages set

frontend/src/components/Recipe/RecipeViewer/Ingredients.vue
Fixes #304
v-list-item already flips the checkbox
=> Fix ingredient checkbox click

frontend/src/components/Admin/General/HomePageSettings.vue, frontend/src/components/UI/LanguageMenu.vue, frontend/src/plugins/vuetify.js, frontend/src/store/modules/language.js
The latest changes I made for Crowdin broke the date picker localization handled by Vuetify.
=> Fix date picker not properly localized

docs/docs/getting-started/install.md
Update docs to reflect the env variable that is actually used.
=> Issue #337 - Update docs for user env

frontend/src/components/MealPlan/ShoppingListDialog.vue
- Fix a dev issue
- Fixes #356
=> Shopping list fixes

frontend/src/components/FormHelpers/ImportOptions.vue, frontend/src/components/UI/Dialogs/BackupDialog.vue, frontend/src/components/UI/Dialogs/ImportDialog.vue, frontend/src/pages/Admin/Dashboard/BackupViewer.vue, mealie/routes/backup_routes.py, mealie/schema/backup.py, mealie/schema/restore.py, mealie/services/backups/exports.py, mealie/services/backups/imports.py
add import / export for notifications
=> notification import/export

frontend/src/components/Recipe/MobileRecipeCard.vue, frontend/src/components/Recipe/RecipeCard.vue, frontend/src/components/UI/Dialogs/BackupDialog.vue, frontend/src/components/UI/Dialogs/BaseDialog.vue, frontend/src/pages/Admin/ManageUsers/TheSignUpTable.vue, frontend/src/pages/Admin/Profile/UserCard.vue, frontend/src/pages/Recipe/ViewRecipe.vue
fallback to icon when no image on recipe
=> fallback to icon when no image

frontend/src/pages/SearchPage/index.vue
Add some padding to the search panel
=> Add padding to the search panel

frontend/public/index.html
This provides a more app-like experience for mobile users that use the "add to homescreen" functionality of their web browsers.
=> Add web manifest

frontend/vue.config.js
Fix for PWA not work on Authelia mentioned on Discord.
=> fix pwa not working behind an authenticated proxy

frontend/package-lock.json, frontend/src/components/Recipe/ContextMenu.vue, frontend/src/components/Recipe/MobileRecipeCard.vue, frontend/src/components/Recipe/RecipeCard.vue, frontend/src/locales/messages/en-US.json
Native web share support for safari and mobile chrome. Copy to clipboard is the fallback, add notification on succes
=> Add Web Share api to ContextMenu.vue

docs/docs/contributors/developers-guide/starting-dev-server.md, makefile, mealie/db/database.py, mealie/db/db_base.py, mealie/routes/deps.py, mealie/routes/recipe/all_recipe_routes.py, mealie/routes/recipe/category_routes.py, mealie/routes/recipe/recipe_crud_routes.py, mealie/routes/recipe/tag_routes.py, mealie/routes/site_settings/site_settings.py, poetry.lock, tests/integration_tests/test_recipe_routes.py
=> add soft fail user dependency

frontend/src/api/recipe.js, frontend/src/pages/Recipe/ViewRecipe.vue, frontend/src/routes/recipes.js
Redirect private recipe to login page if unauthorized
=> fix unauthorized recipe

frontend/src/components/UI/TheAppBar.vue, frontend/src/locales/messages/en-US.json
Switch to light mode/dark mode
=> add translate on toggle theme mode

frontend/src/components/Recipe/Parts/Ingredients.vue
=> Always display ingredients in edit mode

docs/docs/changelog/v0.5.1.md, docs/mkdocs.yml, frontend/package-lock.json, frontend/src/components/UI/CardSection.vue, frontend/src/pages/MealPlan/Planner.vue, mealie/core/config.py, mealie/services/backups/imports.py, mealie/services/scheduler/scheduled_jobs.py, pyproject.toml
fixes icons issues
fixes global scheduler when new group is created
=> Bug fixes/v0.5.1

frontend/src/api/meta.js, mealie/core/config.py
=> Fix about page

frontend/src/locales/messages/en-US.json, frontend/src/pages/Admin/Dashboard/BackupViewer.vue, frontend/src/pages/Admin/Dashboard/EventViewer.vue
=> Add Confirmation Dialogs

frontend/src/components/Recipe/PrintView.vue
Add multiple columns depending on list length.
=> Printview columns

frontend/src/components/Recipe/PrintView.vue
=> Revert "Printview columns"

docs/docs/documentation/community-guide/home-assistant.md
As mentioned in https://github.com/hay-kot/mealie/pull/549#issuecomment-865640385, new PR to `dev` branch
=> Added info on how the Sensor in HA is created

frontend/src/components/Recipe/Parts/Assets.vue, frontend/src/components/Recipe/Parts/Helpers/SettingsMenu.vue, frontend/src/locales/messages/en-US.json
@zierbeek FYI, I believe you wanted to know the outcome of this.
=> Add label to assets icons

frontend/src/components/UI/TheRecipeFab.vue, frontend/src/components/UI/TheSidebar.vue, frontend/src/locales/messages/en-US.json, frontend/src/pages/Admin/Profile/UserCard.vue, frontend/src/plugins/vuetify.js, frontend/src/store/modules/language.js
- Localize recipe import popup
- Add Italian language 
- Dedicated strings for the sidebar (this will allow translators to use shorter texts, so the text is not truncated, without impacting other uses)
=> Localization

docker-compose.yml, docs/docs/documentation/getting-started/install.md, gunicorn_conf.py
tmpfs is not necessary, so I'm remove it.
=> Remove tmpfs

frontend/src/plugins/vuetify.js, frontend/src/store/modules/language.js
Allows for British date format (native in vue-i18n) + potential spelling adaptations.
Requested on Discord.
=> Add support for en-GB

mealie/routes/deps.py, mealie/routes/users/crud.py, mealie/services/image/image.py
Fix a couple errors and code warnings from [LGTM](https://lgtm.com/), an online code scanner.
=> address LGTM errors and warnings
